# lab2 Makefile
.PHONY: smoke wave clean
smoke:
	@echo "[lab2] compile + run smoke"
	# TODO(student): vlog -f filelist.f ; vsim -c tb_top -do "run -all; quit"
wave:
	# TODO(student): generate FSDB
clean:
	rm -rf work transcript *.log *.fsdb *.vcd waves
