# lab3 Makefile
.PHONY: smoke regress wave clean
smoke:
	@echo "[lab3] e2e smoke"
	# TODO(student): vlog -f filelist.f ; vsim -c tb_top -do "run -all; quit"
regress:
	@echo "[lab3] regress (必做 3 项)"
	# TODO(student): loop over tests
wave:
	# TODO(student)
clean:
	rm -rf work transcript *.log *.fsdb *.vcd waves
